FROM alpine:3.5

ENV GOPATH /go
ENV GOBIN /usr/local/bin

RUN apk --no-cache add go git glide build-base ca-certificates \
  && git config --global http.https://gopkg.in.followRedirects true

COPY . /go/src/github.com/progrium/cmd
WORKDIR /go/src/github.com/progrium/cmd

RUN glide install --strip-vendor
RUN go install ./cmd/cmd
