baseurl = "https://gliderlabs.com/cmd/" # "https://www.cmd.io/"
languageCode = "en-us"
title = "Cmd Documentation"
theme = "www"
metadataformat = "yaml"
canonifyurls = true
googleAnalytics = ""

[params]
	name = "Cmd"
	description = "Shell commands in the cloud."

	github_user   = "digitalcraftsman"
	github_repo   = "hugo-alabaster-theme"
	github_banner = true

	custom_css = []
	custom_js  = []

	highlightjs = "css/highlight.css"
	favicon = "favicon.ico"
