apiVersion: v1
kind: ConfigMap
metadata:
  name: cmd-dev
data:
  config.toml: |-

    [dockerbox]
    hostname = "dockerbox.default.svc.cluster.local"

    [store]
    backend = "store.dynamodb"

    [dynamodb]
    table = "dev.cmd.io_cmds"
    token_table = "dev.cmd.io_tokens"
    endpoint = "http://dynamodb:80"
    region = "local"

    [auth0]
    domain = "gl-cmd.auth0.com"
    callback_url = "https://alpha.cmd.io/_auth/callback"
    logout_url = "https://alpha.cmd.io/_auth/logout"

    [mailgun]
    domain = "gliderlabs.com"

    [ssh]
    listen_addr = ":22"
    hostkey_pem = "/tmp/data/id_host"

    [web]
    listen_addr = ":80"

    [analytics]
    tracking_id = "UA-58928488-4"

    [access]
    enabled = false

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cmd-dev
spec:
  replicas: 2
  revisionHistoryLimit: 4
  progressDeadlineSeconds: 90
  template:
    metadata:
      labels:
        app: cmd
        channel: dev
    spec:
      containers:
        - name: cmd
          imagePullPolicy: IfNotPresent
          image: gliderlabs/cmd:latest
          command: ["/usr/local/bin/cmd", "-d", "/config/config.toml"]
          ports:
            - name: http
              containerPort: 80
            - name: ssh
              containerPort: 22
          readinessProbe:
            tcpSocket:
              port: ssh
            initialDelaySeconds: 5
          volumeMounts:
            - mountPath: /tmp/data/
              name: host-key
            - mountPath: /config
              name: config-volume
          env:
            - name: CHANNEL
              value: dev
            - name: SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gliderlabs
                  key: slack-token
            - name: ACCESS_GH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gliderlabs
                  key: github-token
            - name: CRYPTO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: cmd-dev
                  key: crypto-secret-key
            - name: DYNAMODB_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: cmd-dev
                  key: aws-access-key
            - name: DYNAMODB_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: cmd-dev
                  key: aws-secret-key
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: cmd-dev
                  key: auth0-client-id
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cmd-dev
                  key: auth0-client-secret
            - name: AUTH0_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cmd-dev
                  key: auth0-api-token
            - name: MAILGIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cmd-dev
                  key: mailgun-api-key
            - name: STRIPE_PUB_KEY
              valueFrom:
                secretKeyRef:
                  name: cmd-dev
                  key: stripe-pub-key
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: cmd-dev
                  key: stripe-secret-key
      volumes:
        - name: host-key
          secret:
            secretName: cmd-dev
            items:
            - key: id_host
              path: id_host
        - name: config-volume
          configMap:
            name: cmd-dev
---
kind: Service
apiVersion: v1
metadata:
  name: cmd-dev
spec:
  type: NodePort
  selector:
    app: cmd
    channel: dev
  ports:
    - name: http
      targetPort: http
      port: 80
    - name: https
      targetPort: http
      port: 443
    - name: ssh
      targetPort: ssh
      port: 22
