kind: PersistentVolume
apiVersion: v1
metadata:
  name: dynamodb-pv
  labels:
    type: dynamodb
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: dynamodb
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dynamodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dynamodb
spec:
  replicas: 1
  revisionHistoryLimit: 4
  progressDeadlineSeconds: 90
  template:
    metadata:
      labels:
        app: dynamodb
    spec:
      volumes:
        - name: dbdata
          persistentVolumeClaim:
            claimName: dynamodb-pvc
      containers:
        - name: dynamodb
          image: peopleperhour/dynamodb
          ports:
            - name: http
              containerPort: 8000
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
          volumeMounts:
            - mountPath: /var/dynamodb_local
              name: dbdata
---
kind: Service
apiVersion: v1
metadata:
  name: dynamodb
spec:
  selector:
    app: dynamodb
  ports:
    - name: http
      targetPort: http
      port: 80
