apiVersion: v1
kind: ConfigMap
metadata:
  name: cmd-beta
data:
  config.toml: |-
    [maint]
    active = true
    allow = "mattaitchison"

    [docker]
    name = "_docker._tcp.sandbox.infra.gl"

    [store]
    backend = "store.dynamodb"

    [dynamodb]
    table = "beta.cmd.io_cmds"
    token_table = "beta.cmd.io_tokens"

    [auth0]
    domain = "gl-cmd.auth0.com"
    callback_url = "https://beta.cmd.io/_auth/callback"
    logout_url = "https://beta.cmd.io/_auth/logout"

    [mailgun]
    domain = "gliderlabs.com"

    [ssh]
    listen_addr = ":22"
    hostkey_pem = "/tmp/data/id_host"

    [web]
    listen_addr = ":80"

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cmd-beta
spec:
  replicas: 2
  revisionHistoryLimit: 4
  progressDeadlineSeconds: 90
  template:
    metadata:
      labels:
        app: cmd
        channel: beta
    spec:
      volumes:
        - name: host-key
          secret:
            secretName: cmd-beta
            items:
            - key: id_host
              path: id_host
        - name: config-volume
          configMap:
            name: cmd-beta
      containers:
        - name: cmd
          image: ${image}
          command: ["/usr/local/bin/cmd", "-d", "/config/config.toml"]
          ports:
            - name: http
              containerPort: 80
            - name: ssh
              containerPort: 22
          readinessProbe:
            tcpSocket:
              port: ssh
            initialDelaySeconds: 5
          volumeMounts:
            - mountPath: /tmp/data/
              name: host-key
            - mountPath: /config
              name: config-volume
          env:
            - name: CHANNEL
              value: beta
            - name: SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gliderlabs
                  key: slack-token
            - name: ACCESS_GH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gliderlabs
                  key: github-token
            - name: CRYPTO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: cmd-beta
                  key: crypto-secret-key
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: cmd-beta
                  key: sentry-dsn
            - name: DYNAMODB_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: cmd-beta
                  key: aws-access-key
            - name: DYNAMODB_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: cmd-beta
                  key: aws-secret-key
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: cmd-beta
                  key: auth0-client-id
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cmd-beta
                  key: auth0-client-secret

---
kind: Service
apiVersion: v1
metadata:
  name: cmd-beta
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:055471703963:certificate/5ce76820-c1b6-4bf3-b462-01bafa699232"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  type: LoadBalancer
  selector:
    app: cmd
    channel: beta
  ports:
    - name: http
      targetPort: http
      port: 80
    - name: https
      targetPort: http
      port: 443
    - name: ssh
      targetPort: ssh
      port: 22
