apiVersion: v1
kind: ConfigMap
metadata:
  name: cmd-beta
data:
  config.toml: |-
    [dockerbox]
    hostname = "dockerbox.cmd.svc.cluster.local"

    [store]
    backend = "store.dynamodb"

    [dynamodb]
    table = "beta.cmd.io_cmds"
    token_table = "beta.cmd.io_tokens"
    region = "us-east-2"

    [auth0]
    domain = "gl-cmd.auth0.com"
    callback_url = "http://beta.cmd.io/_auth/callback"
    logout_url = "http://beta.cmd.io/_auth/logout"

    [mailgun]
    domain = "gliderlabs.com"

    [ssh]
    listen_addr = ":22"
    hostkey_pem = "/tmp/data/id_host"

    [web]
    listen_addr = ":80"
    tls_addr = ":443"
    tls_cert = "/tmp/tls/tls.crt"
    tls_key = "/tmp/tls/tls.key"


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cmd-beta
spec:
  replicas: 2
  revisionHistoryLimit: 4
  progressDeadlineSeconds: 90
  template:
    metadata:
      labels:
        app: cmd
        channel: beta
    spec:
      volumes:
        - name: host-key
          secret:
            secretName: cmd-beta
            items:
            - key: id_host
              path: id_host
        - name: config-volume
          configMap:
            name: cmd-beta
        - name: tls-cert
          secret:
            secretName: cmd-beta-tls
      containers:
        - name: cmd
          image: us.gcr.io/gliderlabs/cmd:{{.tag}}
          command: ["/usr/local/bin/cmd", "-d", "/config/config.toml"]
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            - name: ssh
              containerPort: 22
          readinessProbe:
            tcpSocket:
              port: ssh
            initialDelaySeconds: 5
          volumeMounts:
            - mountPath: /tmp/data/
              name: host-key
            - mountPath: /config
              name: config-volume
            - mountPath: /tmp/tls
              name: tls-cert
          env:
            - name: CHANNEL
              value: beta
            - name: SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gliderlabs
                  key: slack-token
            - name: ACCESS_GH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gliderlabs
                  key: github-token
            - name: CRYPTO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: cmd-beta
                  key: crypto-secret-key
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: cmd-beta
                  key: sentry-dsn
            - name: DYNAMODB_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: cmd-beta
                  key: aws-access-key
            - name: DYNAMODB_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: cmd-beta
                  key: aws-secret-key
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: cmd-beta
                  key: auth0-client-id
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cmd-beta
                  key: auth0-client-secret
            - name: AUTH0_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cmd-beta
                  key: auth0-api-token
            - name: HONEYCOMB_KEY
              valueFrom:
                secretKeyRef:
                  name: cmd-beta
                  key: honeycomb-key
            - name: MAILGIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cmd-beta
                  key: mailgun-api-key
            - name: STRIPE_PUB_KEY
              valueFrom:
                secretKeyRef:
                  name: cmd-beta
                  key: stripe-pub-key
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: cmd-beta
                  key: stripe-secret-key
---
kind: Service
apiVersion: v1
metadata:
  name: cmd-beta
spec:
  type: LoadBalancer
  selector:
    app: cmd
    channel: beta
  ports:
    - name: http
      targetPort: http
      port: 80
    - name: https
      targetPort: https
      port: 443
    - name: ssh
      targetPort: ssh
      port: 22
